server:
  port: 8080

spring:
  application:
    name: langchain4j-getting-started

# Azure OpenAI Configuration
# These values can be overridden by environment variables
azure:
  openai:
    endpoint: ${AZURE_OPENAI_ENDPOINT:}
    api-key: ${AZURE_OPENAI_API_KEY:}
    deployment: ${AZURE_OPENAI_DEPLOYMENT:}
    temperature: 0.2
    max-tokens: 1000

# Logging configuration
logging:
  level:
    dev.rory.azure.langchain4j: INFO
    dev.langchain4j: INFO

# Values are read from environment variables (see .env.example)